name: 'Mongo trial'
on: push

jobs:
  # Label of the container job
  runner-job:
    # You must use a Linux environment when using service containers or container jobs
    runs-on: ubuntu-latest
    container: node:latest

    # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      mongo:
        # Docker Hub image
        image: mongo:latest
        #
        ports:
          # Opens tcp port 6379 on the host and service container
          - 27017:27017

    steps:
      - name: Check out the repository code
        uses: actions/checkout@v2
      
      - name: install dependencies
        uses: npm install
    
      - name: Try to exec the script for mongo
        run : node run.js

  